enabled_string = "ó± ½ VPN enabled ğŸ”"
disabled_string = "ó°¢‰ VPN disabled ğŸ”“"
lookup = false

[enabled_style]
color = "green"
format = ["bold", "strikethrough"]

[disabled_style]
color = "blue"
format = ["reversed", "italic"]
